### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by fabtho** [bjo3rnf/dmailsubscribe#18]
Hi Björn 

I did a german translation (partly) How do you want to deal with translations?  I just added it to locallang.xml. But there are better options ..

**Comment by cedricziel** [comment]
Why not through the translation server?

**Comment by bjo3rnf** [comment]
> Why not through the translation server?

Is XLIFF required for that?

**Comment by fabtho** [comment]
I don't know how this works. But if you opening a project on typo3 translation server. I would provide my strings.

**Comment by bjo3rnf** [comment]
> I don't know how this works.

Me neither ^^. @cedricziel?

**Comment by cedricziel** [comment]
Sure. Let me find my LMGTFY sticker.

**Comment by bjo3rnf** [comment]
I converted ``locallang.xml`` to XLIFF and would happily accept a PR providing ``de.locallang.xlf``.
