### ISSUE TITLE
Oops, an error occurred! Code: 20160807212253d3370674

### ISSUE THREAD

**Issue by joakim1** [bjo3rnf/dmailsubscribe#23]
I'm getting this error instead of subscription form.

**Comment by cedricziel** [comment]
Please post the content of the relevant log entry.

**Comment by joakim1** [comment]
Sun, 07 Aug 2016 21:38:34 +0000 [ALERT] request="416691decde01" component="TYPO3.CMS.Frontend.ContentObject.Exception.ProductionExceptionHandler": Oops, an error occurred! Code: 201608072138337e6bbff7 - {"exception":"ReflectionException: Class DPN\\Dmailsubscribe\\Controller\\SubscriptionController does not exist in \/var\/typo3_src\/typo3_src-7.6.6\/typo3\/sysext\/extbase\/Classes\/Object\/Container\/ClassInfoFactory.php:35\nStack trace:\n#0 \/var\/typo3_src\/typo3_src-7.6.6\/typo3\/sysext\/extbase\/Classes\/Object\/Container\/ClassInfoFactory.php(35): ReflectionClass->__construct('DPN\\\\Dmailsubscr...')\n#1 \/var\/typo3_src\/typo3_src-7.6.6\/typo3\/sysext\/extbase\/Classes\/Object\/Container\/Container.php(349): TYPO3\\CMS\\Extbase\\Object\\Container\\ClassInfoFactory->buildClassInfoFromClassName('DPN\\\\Dmailsubscr...')\n#2 \/var\/typo3_src\/typo3_src-7.6.6\/typo3\/sysext\/extbase\/Classes\/Object\/Container\/Container.php(173): TYPO3\\CMS\\Extbase\\Object\\Container\\Container->getClassInfo('DPN\\\\Dmailsubscr...')\n#3 \/var\/typo3_src\/typo3_src-7.6.6\/typo3\/sysext\/extbase\/Classes\/Object\/Container\/Container.php(126): TYPO3\\CMS\\Extbase\\Object\\Container\\Container->getInstanceInternal('DPN\\\\Dmailsubscr...', Array)\n#4 \/var\/typo3_src\/typo3_src-7.6.6\/typo3\/sysext\/extbase\/Classes\/Object\/ObjectManager.php(99): TYPO3\\CMS\\Extbase\\Object\\Container\\Container->getInstance('DPN\\\\Dmailsubscr...', Array)\n#5 \/var\/typo3_src\/typo3_src-7.6.6\/typo3\/sysext\/extbase\/Classes\/Mvc\/Dispatcher.php(115): TYPO3\\CMS\\Extbase\\Object\\ObjectManager->get('DPN\\\\Dmailsubscr...')\n#6 \/var\/typo3_src\/typo3_src-7.6.6\/typo3\/sysext\/extbase\/Classes\/Mvc\/Dispatcher.php(84): TYPO3\\CMS\\Extbase\\Mvc\\Dispatcher->resolveController(Object(TYPO3\\CMS\\Extbase\\Mvc\\Web\\Request))\n#7 \/var\/typo3_src\/typo3_src-7.6.6\/typo3\/sysext\/extbase\/Classes\/Mvc\/Web\/FrontendRequestHandler.php(69): TYPO3\\CMS\\Extbase\\Mvc\\Dispatcher->dispatch(Object(TYPO3\\CMS\\Extbase\\Mvc\\Web\\Request), Object(TYPO3\\CMS\\Extbase\\Mvc\\Web\\Response))\n#8 \/var\/typo3_src\/typo3_src-7.6.6\/typo3\/sysext\/extbase\/Classes\/Core\/Bootstrap.php(206): TYPO3\\CMS\\Extbase\\Mvc\\Web\\FrontendRequestHandler->handleRequest()\n#9 \/var\/typo3_src\/typo3_src-7.6.6\/typo3\/sysext\/extbase\/Classes\/Core\/Bootstrap.php(193): TYPO3\\CMS\\Extbase\\Core\\Bootstrap->handleRequest()\n#10 [internal function]: TYPO3\\CMS\\Extbase\\Core\\Bootstrap->run('', Array)\n#11 \/var\/typo3_src\/typo3_src-7.6.6\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(7315): call_user_func_array(Array, Array)\n#12 \/var\/typo3_src\/typo3_src-7.6.6\/typo3\/sysext\/frontend\/Classes\/ContentObject\/UserContentObject.php(40): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->callUserFunction('TYPO3\\\\CMS\\\\Extba...', Array, '')\n#13 \/var\/typo3_src\/typo3_src-7.6.6\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(943): TYPO3\\CMS\\Frontend\\ContentObject\\UserContentObject->render(Array)\n#14 \/var\/typo3_src\/typo3_src-7.6.6\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(859): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->render(Object(TYPO3\\CMS\\Frontend\\ContentObject\\UserContentObject), Array)\n#15 \/var\/typo3_src\/typo3_src-7.6.6\/typo3\/sysext\/frontend\/Classes\/Controller\/TypoScriptFrontendController.php(3566): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('USER', Array)\n#16 \/var\/typo3_src\/typo3_src-7.6.6\/typo3\/sysext\/frontend\/Classes\/Controller\/TypoScriptFrontendController.php(3511): TYPO3\\CMS\\Frontend\\Controller\\TypoScriptFrontendController->INTincScript_process(Array)\n#17 \/var\/typo3_src\/typo3_src-7.6.6\/typo3\/sysext\/frontend\/Classes\/Controller\/TypoScriptFrontendController.php(3477): TYPO3\\CMS\\Frontend\\Controller\\TypoScriptFrontendController->recursivelyReplaceIntPlaceholdersInContent()\n#18 \/var\/typo3_src\/typo3_src-7.6.6\/typo3\/sysext\/frontend\/Classes\/Http\/RequestHandler.php(232): TYPO3\\CMS\\Frontend\\Controller\\TypoScriptFrontendController->INTincScript()\n#19 \/var\/typo3_src\/typo3_src-7.6.6\/typo3\/sysext\/core\/Classes\/Core\/Bootstrap.php(302): TYPO3\\CMS\\Frontend\\Http\\RequestHandler->handleRequest(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#20 \/var\/typo3_src\/typo3_src-7.6.6\/typo3\/sysext\/frontend\/Classes\/Http\/Application.php(78): TYPO3\\CMS\\Core\\Core\\Bootstrap->handleRequest(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#21 \/var\/typo3_src\/typo3_src-7.6.6\/index.php(33): TYPO3\\CMS\\Frontend\\Http\\Application->run()\n#22 \/var\/typo3_src\/typo3_src-7.6.6\/index.php(34): {closure}()\n#23 {main}\n\nNext TYPO3\\CMS\\Extbase\\Object\\Container\\Exception\\UnknownObjectException: Could not analyse class: \"DPN\\Dmailsubscribe\\Controller\\SubscriptionController\" maybe not loaded or no autoloader? Class DPN\\Dmailsubscribe\\Controller\\SubscriptionController does not exist in \/var\/typo3_src\/typo3_src-7.6.6\/typo3\/sysext\/extbase\/Classes\/Object\/Container\/ClassInfoFactory.php:37\nStack trace:\n#0 \/var\/typo3_src\/typo3_src-7.6.6\/typo3\/sysext\/extbase\/Classes\/Object\/Container\/Container.php(349): TYPO3\\CMS\\Extbase\\Object\\Container\\ClassInfoFactory->buildClassInfoFromClassName('DPN\\\\Dmailsubscr...')\n#1 \/var\/typo3_src\/typo3_src-7.6.6\/typo3\/sysext\/extbase\/Classes\/Object\/Container\/Container.php(173): TYPO3\\CMS\\Extbase\\Object\\Container\\Container->getClassInfo('DPN\\\\Dmailsubscr...')\n#2 \/var\/typo3_src\/typo3_src-7.6.6\/typo3\/sysext\/extbase\/Classes\/Object\/Container\/Container.php(126): TYPO3\\CMS\\Extbase\\Object\\Container\\Container->getInstanceInternal('DPN\\\\Dmailsubscr...', Array)\n#3 \/var\/typo3_src\/typo3_src-7.6.6\/typo3\/sysext\/extbase\/Classes\/Object\/ObjectManager.php(99): TYPO3\\CMS\\Extbase\\Object\\Container\\Container->getInstance('DPN\\\\Dmailsubscr...', Array)\n#4 \/var\/typo3_src\/typo3_src-7.6.6\/typo3\/sysext\/extbase\/Classes\/Mvc\/Dispatcher.php(115): TYPO3\\CMS\\Extbase\\Object\\ObjectManager->get('DPN\\\\Dmailsubscr...')\n#5 \/var\/typo3_src\/typo3_src-7.6.6\/typo3\/sysext\/extbase\/Classes\/Mvc\/Dispatcher.php(84): TYPO3\\CMS\\Extbase\\Mvc\\Dispatcher->resolveController(Object(TYPO3\\CMS\\Extbase\\Mvc\\Web\\Request))\n#6 \/var\/typo3_src\/typo3_src-7.6.6\/typo3\/sysext\/extbase\/Classes\/Mvc\/Web\/FrontendRequestHandler.php(69): TYPO3\\CMS\\Extbase\\Mvc\\Dispatcher->dispatch(Object(TYPO3\\CMS\\Extbase\\Mvc\\Web\\Request), Object(TYPO3\\CMS\\Extbase\\Mvc\\Web\\Response))\n#7 \/var\/typo3_src\/typo3_src-7.6.6\/typo3\/sysext\/extbase\/Classes\/Core\/Bootstrap.php(206): TYPO3\\CMS\\Extbase\\Mvc\\Web\\FrontendRequestHandler->handleRequest()\n#8 \/var\/typo3_src\/typo3_src-7.6.6\/typo3\/sysext\/extbase\/Classes\/Core\/Bootstrap.php(193): TYPO3\\CMS\\Extbase\\Core\\Bootstrap->handleRequest()\n#9 [internal function]: TYPO3\\CMS\\Extbase\\Core\\Bootstrap->run('', Array)\n#10 \/var\/typo3_src\/typo3_src-7.6.6\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(7315): call_user_func_array(Array, Array)\n#11 \/var\/typo3_src\/typo3_src-7.6.6\/typo3\/sysext\/frontend\/Classes\/ContentObject\/UserContentObject.php(40): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->callUserFunction('TYPO3\\\\CMS\\\\Extba...', Array, '')\n#12 \/var\/typo3_src\/typo3_src-7.6.6\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(943): TYPO3\\CMS\\Frontend\\ContentObject\\UserContentObject->render(Array)\n#13 \/var\/typo3_src\/typo3_src-7.6.6\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(859): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->render(Object(TYPO3\\CMS\\Frontend\\ContentObject\\UserContentObject), Array)\n#14 \/var\/typo3_src\/typo3_src-7.6.6\/typo3\/sysext\/frontend\/Classes\/Controller\/TypoScriptFrontendController.php(3566): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('USER', Array)\n#15 \/var\/typo3_src\/typo3_src-7.6.6\/typo3\/sysext\/frontend\/Classes\/Controller\/TypoScriptFrontendController.php(3511): TYPO3\\CMS\\Frontend\\Controller\\TypoScriptFrontendController->INTincScript_process(Array)\n#16 \/var\/typo3_src\/typo3_src-7.6.6\/typo3\/sysext\/frontend\/Classes\/Controller\/TypoScriptFrontendController.php(3477): TYPO3\\CMS\\Frontend\\Controller\\TypoScriptFrontendController->recursivelyReplaceIntPlaceholdersInContent()\n#17 \/var\/typo3_src\/typo3_src-7.6.6\/typo3\/sysext\/frontend\/Classes\/Http\/RequestHandler.php(232): TYPO3\\CMS\\Frontend\\Controller\\TypoScriptFrontendController->INTincScript()\n#18 \/var\/typo3_src\/typo3_src-7.6.6\/typo3\/sysext\/core\/Classes\/Core\/Bootstrap.php(302): TYPO3\\CMS\\Frontend\\Http\\RequestHandler->handleRequest(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#19 \/var\/typo3_src\/typo3_src-7.6.6\/typo3\/sysext\/frontend\/Classes\/Http\/Application.php(78): TYPO3\\CMS\\Core\\Core\\Bootstrap->handleRequest(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#20 \/var\/typo3_src\/typo3_src-7.6.6\/index.php(33): TYPO3\\CMS\\Frontend\\Http\\Application->run()\n#21 \/var\/typo3_src\/typo3_src-7.6.6\/index.php(34): {closure}()\n#22 {main}"}

**Comment by cedricziel** [comment]
Did you try to clear the autoload cache? 

IMHO that's easily solvable with a autoloader map in ext_emconf, unless some other extension that's alphabetically before dmailsubscribe errors while the map is created

**Comment by joakim1** [comment]
Deleted contents of typo3temp/autoload/ and it works now. Thank you very much.
